# Generated by Django 3.1.7 on 2021-03-25 01:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='job_url',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
        migrations.RemoveField(
            model_name='location',
            name='area',
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='employer',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='job_role',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='work_type',
            field=models.TextField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='company',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_listed',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 1, 26, 43, 913220, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='job_title',
            field=models.TextField(default='', max_length=100),
        ),
    ]
