# Generated by Django 3.1.7 on 2021-03-25 01:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210325_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_listed',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 1, 26, 58, 476456, tzinfo=utc)),
        ),
    ]
