# Generated by Django 3.1.7 on 2021-03-25 01:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210325_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='region',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.location'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_listed',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 1, 28, 51, 183453, tzinfo=utc)),
        ),
    ]
