# Generated by Django 3.1.7 on 2021-03-25 01:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210325_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_listed',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 1, 36, 51, 406330, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(default='', max_length=100, unique=True),
        ),
    ]
