# Generated by Django 3.1.7 on 2021-03-29 00:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210329_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='city',
            new_name='sub_region',
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_listed',
            field=models.DateField(default=datetime.datetime(2021, 3, 29, 0, 37, 11, 840499, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='region',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='location',
        ),
    ]
