# Generated by Django 3.1.7 on 2021-04-14 05:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210413_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(default='', max_length=100)),
                ('pay', models.IntegerField(default=0)),
                ('lower_pay', models.IntegerField(default=0)),
                ('upper_pay', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_listed',
            field=models.DateField(default=datetime.datetime(2021, 4, 14, 5, 43, 34, 71224, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Job_Type_Pay',
        ),
    ]
