# Generated by Django 3.1.7 on 2021-04-14 09:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20210414_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_language_count',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_listed',
            field=models.DateField(default=datetime.datetime(2021, 4, 14, 9, 27, 7, 360424, tzinfo=utc)),
        ),
    ]
