# Generated by Django 3.1.7 on 2021-04-14 09:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210414_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_language_count',
            name='count',
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_listed',
            field=models.DateField(default=datetime.datetime(2021, 4, 14, 9, 42, 8, 325231, tzinfo=utc)),
        ),
    ]
