# Generated by Django 3.1.7 on 2021-05-22 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20210522_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softskill', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_listed',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 11, 22, 50, 738868, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='SoftSkills_Listing_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.softskills')),
                ('listings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.listing')),
            ],
        ),
    ]
