# Generated by Django 3.1.7 on 2021-05-22 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20210522_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softskills_listing_count',
            old_name='framework',
            new_name='softskill',
        ),
        migrations.AlterField(
            model_name='listing',
            name='date_listed',
            field=models.DateField(default=datetime.datetime(2021, 5, 22, 11, 27, 6, 241500, tzinfo=utc)),
        ),
    ]
